"""Initialize Sentinel ontology and ingest policy documents into Neo4j.

This script bootstraps the foundational graph for Sentinel GraphRAG by:
1) Creating a fixed SME-governed ontology of policy categories.
2) Generating synthetic banking policy documents.
3) Running Curator extraction via Groq with strict Pydantic output.
4) Persisting policies and supersession chains into Neo4j.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Dict, List, Literal, Optional, Sequence

from langchain_huggingface import HuggingFaceEndpointEmbeddings
from langchain_groq import ChatGroq
from neo4j import Driver, GraphDatabase
from neo4j.exceptions import Neo4jError, ServiceUnavailable
from pydantic import BaseModel, Field
from pydantic import ValidationError
from dotenv import load_dotenv, find_dotenv

CATEGORY_VALUES: tuple[str, ...] = (
    "Retail_Loans", "Corporate_Banking", "KYC_AML", "Credit_Cards", 
    "Tax_Compliance", "Foreign_Exchange_FEMA", "Digital_Payments_UPI", 
    "Risk_Management", "Priority_Sector_Lending", "Audit_And_Inspection",
)

TargetCategory = Literal[
    "Retail_Loans", "Corporate_Banking", "KYC_AML", "Credit_Cards", 
    "Tax_Compliance", "Foreign_Exchange_FEMA", "Digital_Payments_UPI", 
    "Risk_Management", "Priority_Sector_Lending", "Audit_And_Inspection",
]
# CATEGORY_VALUES = [
#     "Retail_Loans", "Corporate_Banking", "KYC_AML", "Credit_Cards", 
#     "Tax_Compliance", "Foreign_Exchange_FEMA", "Digital_Payments_UPI", 
#     "Risk_Management", "Priority_Sector_Lending", "Audit_And_Inspection"
# ]
ActionType = Literal["CREATE_NEW", "SUPERSEDE_OLD"]
DEFAULT_ACCESS_CODE = 2

CURATOR_PROMPT_TEMPLATE: str = """
You are Sentinel Curator Agent for Tier-1 banking governance.
Classify the policy into one ontology category and determine if this policy supersedes an old one.
Identify any specific customer types this policy applies to (e.g., NRI, MSME) and list them in applies_to_customer.
Identify any specific documents or collateral required by this policy and list them in requires_document.
If none are mentioned, return empty lists for both fields.
Return only fields required by the schema.

Ontology categories: {categories}

Document Name: {document_name}
Issue Date: {issue_date}
Document Text:
{document_text}
""".strip()
def _load_and_sanitize_env():
    load_dotenv()
    find_dotenv()
    raw_key = os.environ.get("GROQ_API_KEY", "").strip().replace('"', "").replace("'", "")
    os.environ["GROQ_API_KEY"] = raw_key
    raw_hf_token = os.environ.get("HF_TOKEN", "").strip().replace('"', "").replace("'", "")
    os.environ["HF_TOKEN"] = raw_hf_token

_load_and_sanitize_env()

class GraphAction(BaseModel):
    """Structured graph mutation action generated by Curator extraction.

    Business logic:
    - target_node binds policy to a fixed SME-governed ontology category.
    - action_type controls whether this policy is a new leaf or supersedes prior guidance.
    - extracted_rule captures the actionable compliance rule for retrieval-time evidence.
    - superseded_document names prior policy to connect supersession lineage.
    """

    target_node: TargetCategory = Field(
        ..., description="Ontology category that the document belongs to."
    )
    action_type: ActionType = Field(
        ..., description="CREATE_NEW for fresh guidance, SUPERSEDE_OLD for replacements."
    )
    extracted_rule: str = Field(
        ..., min_length=10, description="Concise compliance rule extracted from the document."
    )
    superseded_document: Optional[str] = Field(
        default=None,
        description="Name of old policy being replaced when action_type is SUPERSEDE_OLD.",
    )
    applies_to_customer: List[str] = Field(
        default_factory=list,
        description="Customer segments this policy applies to (for APPLIES_TO edges).",
    )
    requires_document: List[str] = Field(
        default_factory=list,
        description="Required documents/collateral for this policy (for REQUIRES edges).",
    )


def initialize_ontology(driver: Driver) -> None:
    """Reset database and create fixed ontology category nodes.

    This function creates the SME-governed root ontology to ensure every ingested
    policy maps to one canonical business category.
    """

    clear_query = "MATCH (n) DETACH DELETE n"
    create_categories_query = """
    UNWIND $categories AS category_name
    MERGE (:Category {name: category_name})
    """

    try:
        with driver.session() as session:
            session.execute_write(lambda tx: tx.run(clear_query).consume())
            session.execute_write(
                lambda tx: tx.run(
                    create_categories_query,
                    categories=list(CATEGORY_VALUES),
                ).consume()
            )
        print("Ontology initialized with Category nodes.")
    except ServiceUnavailable as error:
        print(f"Neo4j connection dropped while initializing ontology: {error}")
        raise
    except Neo4jError as error:
        print(f"Neo4j error while initializing ontology: {error}")
        raise
    except Exception as error:
        print(f"Unexpected error while initializing ontology: {error}")
        raise


def create_policy_vector_index(driver: Driver, embedding_dimensions: int) -> None:
    """Create Neo4j vector index for semantic policy retrieval."""

    create_index_query = """
    CREATE VECTOR INDEX policy_embeddings IF NOT EXISTS
    FOR (n:Policy) ON (n.embedding)
    OPTIONS {
      indexConfig: {
        `vector.dimensions`: $dimensions,
        `vector.similarity_function`: 'cosine'
      }
    }
    """

    try:
        with driver.session() as session:
            session.execute_write(
                lambda tx: tx.run(
                    create_index_query,
                    dimensions=embedding_dimensions,
                ).consume()
            )
        print(
            "Vector index ready: policy_embeddings "
            f"(dimensions={embedding_dimensions}, similarity=cosine)."
        )
    except ServiceUnavailable as error:
        print(f"Neo4j connection dropped while creating vector index: {error}")
        raise
    except Neo4jError as error:
        print(f"Neo4j error while creating vector index: {error}")
        raise


def create_policy_fulltext_index(driver: Driver) -> None:
    """Create Neo4j full-text index for keyword-backed hybrid retrieval."""

    create_index_query = """
    CREATE FULLTEXT INDEX policy_keywords IF NOT EXISTS
    FOR (n:Policy)
    ON EACH [n.name, n.extracted_rule, n.source_text]
    """

    try:
        with driver.session() as session:
            session.execute_write(lambda tx: tx.run(create_index_query).consume())
        print("Full-text index ready: policy_keywords (name, extracted_rule, source_text).")
    except ServiceUnavailable as error:
        print(f"Neo4j connection dropped while creating full-text index: {error}")
        raise
    except Neo4jError as error:
        print(f"Neo4j error while creating full-text index: {error}")
        raise


def get_mock_documents() -> List[Dict[str, str]]:
    """Return synthetic banking compliance memos for ingestion tests.

    Includes an older AML policy and a newer urgent circular that supersedes it,
    plus an unrelated retail loan policy to validate category routing.
    """

    return [
        {
            "name": "AML_2024_PAN_Limit_Memo",
            "issue_date": "2024-04-15",
            "text": (
                "For cash deposits above INR 100,000 in a single day, customers must "
                "provide PAN or Form 60. Branch staff must retain transaction logs for "
                "audit review and escalate repeated threshold breaches to AML compliance."
            ),
        },
        {
            "name": "AML_2026_Urgent_Update",
            "issue_date": "2026-01-10",
            "text": (
                "This urgent circular supersedes AML_2024_PAN_Limit_Memo. For cash "
                "deposits above INR 50,000, PAN verification is mandatory. Branch staff "
                "must capture customer segment details and retain supporting identity "
                "documents for monitoring and reporting."
            ),
        },
        {
            "name": "Retail_NRI_Home_Loan_Policy",
            "issue_date": "2025-08-01",
            "text": (
                "NRI home loan applications require passport copy, overseas address proof, "
                "and salary slips. The interest rate starts at 8.35% p.a. with a maximum "
                "loan amount of INR 20,000,000 subject to credit approval."
            ),
        },
    ]


def process_and_ingest(
    driver: Driver,
    llm: ChatGroq,
    embeddings_model: HuggingFaceEndpointEmbeddings,
    documents: List[Dict[str, str]],
) -> None:
    """Extract graph actions with Groq and write policy lineage into Neo4j.

    Business logic:
    - Creates one Policy node per source document and links it to Category via BELONGS_TO.
    - On SUPERSEDE_OLD, updates supersession chain by creating SUPERSEDES edge from
      new policy to prior policy and marks old policy inactive.
    """

    structured_llm = llm.with_structured_output(GraphAction)

    create_policy_query = """
    MATCH (c:Category {name: $category_name})
    CREATE (p:Policy {
        name: $policy_name,
        issue_date: $issue_date,
        source_text: $source_text,
        extracted_rule: $extracted_rule,
        embedding: $embedding,
        action_type: $action_type,
        access_code: $access_code,
        active: true,
        created_at: datetime($created_at)
    })
    MERGE (p)-[:BELONGS_TO]->(c)
    WITH p
    UNWIND (CASE WHEN size($applies_to_customer) > 0 THEN $applies_to_customer ELSE [null] END) AS customer
    FOREACH (ignoreMe IN CASE WHEN customer IS NOT NULL THEN [1] ELSE [] END |
        MERGE (ct:CustomerType {name: customer})
        MERGE (p)-[:APPLIES_TO]->(ct)
    )
    WITH p
    UNWIND (CASE WHEN size($requires_document) > 0 THEN $requires_document ELSE [null] END) AS doc
    FOREACH (ignoreMe IN CASE WHEN doc IS NOT NULL THEN [1] ELSE [] END |
        MERGE (dr:DocumentRequirement {name: doc})
        MERGE (p)-[:REQUIRES]->(dr)
    )
    RETURN p.name AS created_policy
    """

    supersede_query = """
    MATCH (new_policy:Policy {name: $new_policy_name})
    MATCH (old_policy:Policy {name: $old_policy_name})
    MERGE (new_policy)-[:SUPERSEDES]->(old_policy)
    SET old_policy.active = false,
        old_policy.retired_at = datetime($retired_at)
    RETURN new_policy.name AS new_policy_name, old_policy.name AS old_policy_name
    """

    for document in documents:
        document_name = document["name"]
        try:
            prompt = CURATOR_PROMPT_TEMPLATE.format(
                categories=", ".join(CATEGORY_VALUES),
                document_name=document_name,
                issue_date=document["issue_date"],
                document_text=document["text"],
            )

            action: GraphAction = structured_llm.invoke(prompt)
            semantic_text = f"{action.extracted_rule}\n\n{document['text']}"
            question_embedding: Sequence[float] = embeddings_model.embed_query(semantic_text)
            embedding = [float(value) for value in question_embedding]
            timestamp = datetime.utcnow().isoformat()

            with driver.session() as session:
                creation_result = session.execute_write(
                    lambda tx: tx.run(
                        create_policy_query,
                        category_name=action.target_node,
                        policy_name=document_name,
                        issue_date=document["issue_date"],
                        source_text=document["text"],
                        extracted_rule=action.extracted_rule,
                        embedding=embedding,
                        action_type=action.action_type,
                        access_code=DEFAULT_ACCESS_CODE,
                        applies_to_customer=action.applies_to_customer,
                        requires_document=action.requires_document,
                        created_at=timestamp,
                    ).single(strict=True)
                )

                print(
                    "Ingested policy:",
                    creation_result["created_policy"],
                    "| category:",
                    action.target_node,
                    "| action:",
                    action.action_type,
                )

                if (
                    action.action_type == "SUPERSEDE_OLD"
                    and action.superseded_document is not None
                ):
                    supersede_result = session.execute_write(
                        lambda tx: tx.run(
                            supersede_query,
                            new_policy_name=document_name,
                            old_policy_name=action.superseded_document,
                            retired_at=timestamp,
                        ).single()
                    )

                    if supersede_result is None:
                        print(
                            "Warning: superseded document not found for",
                            f"{document_name} -> {action.superseded_document}",
                        )
                    else:
                        print(
                            "Supersession linked:",
                            f"{supersede_result['new_policy_name']} -> "
                            f"{supersede_result['old_policy_name']}",
                        )
        except ServiceUnavailable as error:
            print(f"Neo4j connection dropped while ingesting {document_name}: {error}")
        except Neo4jError as error:
            print(f"Neo4j error while ingesting {document_name}: {error}")
        except ValidationError as error:
            print(f"Structured output validation failed for {document_name}: {error}")
        except Exception as error:
            print(f"LLM/parsing error while ingesting {document_name}: {error}")


def build_neo4j_driver() -> Driver:
    """Create Neo4j driver from environment configuration."""

    uri = os.getenv("NEO4J_URI")
    user = os.getenv("NEO4J_USER") or os.getenv("NEO4J_USERNAME")
    password = os.getenv("NEO4J_PASSWORD")

    if not uri or not user or not password:
        raise ValueError("NEO4J_URI, NEO4J_USER/NEO4J_USERNAME, and NEO4J_PASSWORD must be set.")

    return GraphDatabase.driver(uri, auth=(user.strip(), password.strip()))


def build_groq_llm() -> ChatGroq:
    """Create Groq chat model client for structured Curator extraction."""

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError("GROQ_API_KEY is not set. Export it before running this script.")

    return ChatGroq(
        model="llama-3.3-70b-versatile",
        api_key=api_key,
        temperature=0,
    )


def build_embeddings_model() -> HuggingFaceEndpointEmbeddings:
    """Create cloud sentence-transformer embeddings client for policy vectors."""

    hf_token = os.getenv("HF_TOKEN")
    if not hf_token:
        raise ValueError("HF_TOKEN is not set. Export it before running this script.")

    return HuggingFaceEndpointEmbeddings(
        model="sentence-transformers/all-MiniLM-L6-v2",
        task="feature-extraction",
        huggingfacehub_api_token=hf_token,
    )


def main() -> None:
    """Initialize ontology and ingest mock policies into graph."""

    driver = build_neo4j_driver()
    driver.verify_connectivity()
    try:
        llm = build_groq_llm()
        embeddings_model = build_embeddings_model()
        embedding_dimensions = len(embeddings_model.embed_query("dimension_probe"))
        initialize_ontology(driver)
        create_policy_vector_index(driver, embedding_dimensions)
        create_policy_fulltext_index(driver)
        documents = get_mock_documents()
        process_and_ingest(driver, llm, embeddings_model, documents)
    finally:
        driver.close()


if __name__ == "__main__":
    main()
